#!/usr/bin/env python3
"""
Script to regenerate the queries.pyi type stub file from SQL files.
"""

import pathlib
import sys
from typing import Dict, Any

# Add the app directory to the path so we can import aiosql
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent))

import aiosql


def generate_queries_types():
    """Generate type stubs for the current SQL queries."""
    sql_path = pathlib.Path(__file__).parent.parent / "app" / "db" / "queries" / "sql"
    output_path = (
        pathlib.Path(__file__).parent.parent / "app" / "db" / "queries" / "queries.pyi"
    )

    print(f"Scanning SQL files in: {sql_path}")
    print(f"Output will be written to: {output_path}")

    # Get all SQL files
    sql_files = list(sql_path.glob("*.sql"))
    print(f"Found SQL files: {[f.name for f in sql_files]}")

    # Generate queries object from all SQL files
    queries = aiosql.from_path(sql_path, "asyncpg")

    # Generate type stub content
    stub_content = generate_type_stub(queries)

    # Write to file
    with open(output_path, "w") as f:
        f.write(stub_content)

    print(f"✅ Generated type stubs for {len(sql_files)} SQL files")
    print(f"📁 Output written to: {output_path}")


def generate_type_stub(queries) -> str:
    """Generate type stub content from queries object."""
    stub_lines = [
        '"""Typings for queries generated by aiosql"""',
        "",
        "from typing import Dict, Optional, Sequence, List, Any",
        "",
        "from asyncpg import Connection, Record",
        "",
    ]

    # Get all query methods from the queries object
    query_methods = []
    for attr_name in dir(queries):
        if not attr_name.startswith("_") and callable(getattr(queries, attr_name)):
            query_methods.append(attr_name)

    # Group methods by their likely mixin classes
    mixins = {
        "TransactionsQueriesMixin": [],
        "StrategiesQueriesMixin": [],
    }

    for method_name in sorted(query_methods):
        if "transaction" in method_name.lower():
            mixins["TransactionsQueriesMixin"].append(method_name)
        elif "strategy" in method_name.lower():
            mixins["StrategiesQueriesMixin"].append(method_name)
        else:
            # Default to strategies for now
            mixins["StrategiesQueriesMixin"].append(method_name)

    # Generate mixin classes
    for mixin_name, methods in mixins.items():
        if methods:
            stub_lines.append(f"class {mixin_name}:")
            for method_name in methods:
                # Get the method object
                method = getattr(queries, method_name)

                # Generate a basic signature (aiosql doesn't expose full type info easily)
                # We'll use a generic signature that can be refined manually
                stub_lines.append(
                    f"    async def {method_name}(self, conn: Connection, **kwargs) -> Record: ..."
                )
                stub_lines.append("")

    # Generate the main Queries class
    stub_lines.append("class Queries(")
    for mixin_name in mixins.keys():
        if mixins[mixin_name]:  # Only include mixins that have methods
            stub_lines.append(f"    {mixin_name},")
    stub_lines.append("): ...")
    stub_lines.append("")
    stub_lines.append("queries: Queries")

    return "\n".join(stub_lines)


if __name__ == "__main__":
    generate_queries_types()
